name: Auto-merge PRs
on:
  pull_request_target:
    types: [opened, synchronize]
    paths:
      - 'Contributors.md' # <- only run if only contributors file changed
    
jobs:
  auto-merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      
    steps:
      
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # checkout PR branch
          ref: ${{ github.event.pull_request.head.sha }}
#           # Fetch the full commit history
#           # fetch-depth: 0
#           # Fetch only the 2 most recent commit
          fetch-depth: 2
        
      # Check if the pull request only modifies the Contributors.md file
      - name: Check if PR only modifies Contributors.md
        id: is_only_contributors_file_changed
        run: |
          # Get a list of files changed in the pull request
          FILES_CHANGED=$(git diff --name-only HEAD HEAD~1)
          
          # Set the files_changed environment variable to the list of changed files
          echo "files_changed=$FILES_CHANGED" >> $GITHUB_ENV
          
          # Check if the list of changed files only contains the Contributors.md file
          if [[ "$FILES_CHANGED" == "Contributors.md" ]]; then
            # Set the only_contributors output variable to 'true'
            # Older way doing it 
            # echo "::set-output name=only_contributors::true"
            # new way doing it
            echo "only_contributors=true" >> $GITHUB_ENV
            echo "The value of only_contributors is $only_contributors in the if block"
          else
            # Set the only_contributors output variable to 'false'
            # echo "::set-output name=only_contributors::false"
            echo "only_contributors=false" >> $GITHUB_ENV
            echo "The value of only_contributors is $only_contributors in else block"
          echo "The value of only_contributors is $only_contributors"
          fi

      # Merge the pull request if it only modifies the Contributors.md file or if it fail to do then drop failure message as post 
      - name: Merge PR
        id: merge_pr
        # older version
        # if: steps.is_only_contributors_file_changed.outputs.only_contributors == 'true'
        # new version
        if: env.only_contributors == 'true'
        uses: actions/github-script@v5
        with:
          script: |
            // Attempt to merge the pull request using the squash method
            const response = await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              merge_method: "squash"
            })
            // console.log(response);
            // Check if the merge was successful by checking the status code of the response
            if (response.status === 200) {
              // Set the merged output variable to 'true'
              // core.setOutput('merged', 'true')
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.issue.number,
                  body: "Hello @" + context.payload.pull_request.user.login + ", congratulations! You've successfully submitted a pull request. 🎉\n\nThanks for your contribution!\n\nIf you liked the tutorial, please star this repo by clicking the star button on the top right of this page. ![](https://camo.githubusercontent.com/e2821336f0dc5009292b8357ad4599e765aa17ad3837420b41db6c59cbbff3a8/68747470733a2f2f6669727374636f6e747269627574696f6e732e6769746875622e696f2f6173736574732f737461722e706e67)\n\n# Next steps\n- Continue contributing: If you're looking for projects to contribute to, checkout our web app [webapp](https://firstcontributions.github.io/).\n- Join our slack group: We have a community to help/support contributors. Slack [Join slack group](https://join.slack.com/t/firstcontributors/shared_invite/zt-vchl8cde-S0KstI_jyCcGEEj7rSTQiA).\n- Share on social media: You can share this content to help more people. Twitter [tweet](https://twitter.com/intent/tweet?text=Yay%21%20I%20just%20made%20my%20first%20open%20source%20contribution%20with%20@1stcontribution.%20You%20can%20too%20at%20https%3A//goo.gl/66Axwe%0A&hashtags=OpenSource,CodeNewbie). Facebook [share](https://www.facebook.com/sharer/sharer.php?u=https://roshanjossey.github.io/first-contributions&quote=Yay%21%20I%20just%20made%20my%20first%20open%20source%20contribution%20with%20First%20Contributions.%20You%20can%20too,%20by%20following%20a%20simple%20tutorial%20at%20https%3A//goo.gl/66Axwe&hashtag=%23OpenSource)\n\nWe'd love to hear your thoughts about this project. Let us know how we can improve by commenting or opening an issue here."
                })
            } else {
              // Set the merged output variable to 'false'
              core.setOutput('merged', 'false')
              
              // Post a comment on the pull request using the createComment method
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: "Something went wrong while attempting to merge this pull request. Please check the GitHub Actions log for more information."
              })
            }

          github-token: ${{ secrets.GITHUB_TOKEN }}



      # Post a comment on the pull request if it was not merged automatically
      - name: Post comment on PR if not merged automatically
        # Check if the pull request only modifies the CONTRIBUTORS.md file
        if: env.only_contributors != 'true'
        uses: actions/github-script@v5
        with:
          script: |
            // Post a comment on the pull request saying that it contains changes in other files too which requires review
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `Thank you for your pull request. This pull request contains changes in files which requires review. The following files were changed:\n\n**${process.env.files_changed}**`
            })
          github-token: ${{ secrets.GITHUB_TOKEN }}



